# Generated by Django 2.2.5 on 2019-10-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diseas',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
