# Generated by Django 2.2.5 on 2019-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191002_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
