# Generated by Django 2.2.5 on 2019-10-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.TextField()),
                ('email', models.EmailField(default='nishit@gmail.com', max_length=250)),
                ('diseas', models.TextField()),
            ],
        ),
    ]
