# Generated by Django 2.2.5 on 2019-10-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_patient_diseas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
