# Generated by Django 2.2.5 on 2019-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_patient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
