# Generated by Django 2.2.5 on 2019-10-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191004_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medihistory',
        ),
    ]
