# Generated by Django 2.2.5 on 2019-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191004_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alergy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medihistory',
            field=models.TextField(default='no history', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='no-value', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diseases',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
