# Generated by Django 2.2.5 on 2019-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191004_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='report',
            field=models.ImageField(default='default.jpg', upload_to='report_pics'),
        ),
    ]
